config/routes.rb
Rails.application.routes.draw do

  # Root Path definition
  root to: 'properties#home'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  get '/profile' => 'pages#profile'
  get '/admin'   => 'pages#admin_party'

  resources :properties do
    resources :bookings
    resources :photos
    resources :tags

  end

  # resources :photos
  resources :users
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id          :integer          not null, primary key
#  username    :string
#  full_name   :string
#  email       :string
#  profile_pic :string
#  user_type   :string
#  description :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  property_id :integer
#

class User < ApplicationRecord
   has_many :properties # owner
   has_many :bookings   # guest/owner

   has_secure_password
   validates :email, presence: true, uniqueness: true
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
     @user = User.new
  end

  def index
    @user = User.all
  end

  def create
    user = User.new(user_params)
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      user.profile_pic = req["public_id"]
      # raise 'hell'
    end
    user.save
    redirect_to user
    
    # user = User.create user_params
    # if user.persisted?
    #   # user successfully created, redirect to profile page for this user
    #   session[:user_id] = user.id
    #   redirect_to user_path user
    # else
    #   # error creating user (probably a validation error)
    #   flash[:errors] = user.errors.full_messages
    #   redirect_to new_user_path
    # end
  end


  def edit
    @user = User.find params[:id]
  end


  def update

  end


  def destroy
  end

  def show
    @user = User.find params[:id]
  end



  private
   def user_params
     params.require(:user).permit(:username, :full_name, :email, :description, :password, :password_confirmation)
   end


end

app/helpers/user_helper.rb
module UserHelper
end

app/views/users/_form.html.erb
<div style = "color:red; font-size:20px">
<%=flash[:error]%>
</div>

<%= form_for @user , html: {multipart: true} do |f| %>

<fieldset>
  <%= f.label :username %>
  <%= f.text_field :username %>
</fieldset>

<fieldset>
  <%= f.label :full_name  %>
  <%= f.text_field :full_name %>
</fieldset>

<fieldset>
  <%= f.label :email %>
  <%= f.text_field :email %>
</fieldset>

<fieldset>
  <%= f.label :description %>
  <%= f.text_field :description %>
</fieldset>

<fieldset>
  <%= f.label :profile_pic %>
  <%= f.cl_image_upload :profile_pic %>
</fieldset>


<%= f.label :password %>
<%= f.password_field :password %>
<br>
<%= f.label :password_confirmation %>
<%= f.password_field :password_confirmation %>


<%= f.submit %>


<% end %>

app/views/users/create.html.erb
<h1>User#create</h1>
<p>Find me in app/views/user/create.html.erb</p>

app/views/users/destroy.html.erb
<h1>User#destroy</h1>
<p>Find me in app/views/user/destroy.html.erb</p>

app/views/users/edit.html.erb
<h2> Edit User Details </h2>

<%= render partial: 'form' %>

app/views/users/home.html.erb
<h1>Property#home</h1>
<p>Find me in app/views/property/home.html.erb</p>


<%= link_to 'USERS', users_path %>

app/views/users/index.html.erb
<h1>Displaying list of Users</h1>
<div class="row">
<% @user.each do |user| %>
  <div class="col-md-10">
    <%= link_to user.full_name , user%>
    <br/>
    <%= cl_image_tag user.profile_pic %>
    <hr>
  </div>
<% end %>
</div>

app/views/users/new.html.erb
<h1>Hi New User, Welcome to Sign Up</h1>

<%= render partial: 'form' %>

app/views/users/show.html.erb
<h2>User details</h2>

<% if @user.profile_pic.present? %>
  <%= cl_image_tag @user.profile_pic %>
<% end %>
<h1> <%=@user.username %></h1>
FullName: <%=@user.full_name %>
<br>
Email   :<%= @user.email %>

<% if ! (@current_user == @user) %>
<a class="btn btn-default" href= "mailto:<%= @user.email %>?bcc=email_2@mywebsite.com?" role="button">
Send Email Now</a>
<br>
<!-- <%= link_to 'Properties', property_path %> -->
<% end %>


<br><hr>
<% if @user.properties.length == 0 %>
  <p> You currently do not own any properties</p>
<% else %>
<p> <u>You current properties:</u></p>
<ul>
<% @user.properties.each do |p| %>
<li><%= p.address %> | <%= link_to 'Go to Property', p %></li>
<% end %>
</ul>
<% end %>