config/routes.rb
Rails.application.routes.draw do

  # Root Path definition
  root to: 'properties#home'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  get '/profile' => 'pages#profile'
  get '/admin'   => 'pages#admin_party'

  resources :properties do
    resources :bookings
    resources :photos
    resources :tags

  end

  # resources :photos
  resources :users
end

app/models/property.rb
# == Schema Information
#
# Table name: properties
#
#  id                :integer          not null, primary key
#  address           :text
#  city              :string
#  price             :float
#  property_type     :string
#  discounts         :string
#  boolean           :string
#  discount_amount   :float
#  has_extended_stay :boolean
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

class Property < ApplicationRecord

   geocoded_by :address
   after_validation :geocode


   belongs_to :user, optional: true # as in owner
   has_many :bookings               # done by guest users/owner users

   has_many :users, through: :bookings # as in guests


   has_many :photos
   has_and_belongs_to_many :tags

end














# ??


# has many reviews , reviews belong to property
#        a review is connected to user thru the property

# location : has many properties, has many users
# property belongs to one location , user belongs to one location

#
# location has many Properties
# Properties have many locations
#



# tags : luxury , holiday , low-budget(non-luxury), long-term-rentals, duplex, tree-house, island, large, small, 1-bedroom , 2 bedroom, 3 bedrooms or more, apartment, scenic,

# property can come under luxury & holiday  -> has_many tags
# tag -> has_many properties

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController

  def home
    @properties = Property.all
    @users      = User.all
  end

  def index
    @properties = Property.all
    # binding.pry
  end

  def show
    @property = Property.find params[:id]
    @photos   = @property.photos
  end

  def new
    @property = Property.new
  end


  def create
    if @current_user.present?
      property = Property.create property_params

    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      property.image = req["public_id"]
    end
    property.save
    @current_user.properties << property
    redirect_to properties_path
    else
      flash[:error] = "You must be logged in to complete action"
      redirect_to login_path
    end

  end

  def edit
    @property = Property.find params[:id]
  end
  #update
  def update
    property = Property.find params[:id]
    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      property.image = req["public_id"]
    end
    property.update_attributes(property_params)
    property.save

    redirect_to property
  end

  def destroy
    Property.destroy params[:id]
    redirect_to properties_path
  end



  private
   def property_params
     params.require(:property).permit(:address, :city, :price, :property_type, :image, :description, :number_of_beds, :number_of_baths, :number_of_parkings, :pets_allowed, :smoking_allowed, :wifi_present, :cancellation_policy )
   end


end

app/helpers/property_helper.rb
module PropertyHelper
end

app/views/properties/_form.html.erb
<%= form_for @property, html: {multipart: true}, class:"form-horizontal" do |f| %>

<div class="form-group">
  <div class=col-sm-10>
<fieldset>
  <%= f.label :address %>
  <%= f.text_field :address ,class:"form-control"%>
</fieldset>
</div>
</div>

<div class="form-group">
  <div class=col-sm-10>
<fieldset>
  <%= f.label :city  %>
  <%= f.text_field :city ,class:"form-control" %>
</fieldset>
</div>
</div>

<div class="form-group">
  <div class=col-sm-10>
<fieldset>
  <%= f.label :price %>
  <%= f.number_field :price , class:"form-control" %>
</fieldset>
</div>
</div>

<div class="form-group">
  <div class=col-sm-10>
<fieldset>
  <%= f.label :property_type %>
  <%= f.text_field :property_type  , class:"form-control"%>
</fieldset>
</div>
</div>

<div class="form-group">
  <div class=col-sm-10>

    <fieldset>
      <%= f.label :image %>
      <%= f.cl_image_upload :image %>
    </fieldset>
</div>
</div>


<div class="form-group">
  <div class=col-sm-10>
<fieldset>
  <%= f.label :description %>
  <%= f.text_field :description ,  class:"form-control" %>
</fieldset>
</div>
</div>


<div class="form-group">
  <div class=col-sm-10>
<fieldset>
  <%= f.label :number_of_beds %>
  <%= f.number_field :number_of_beds ,  class:"form-control" %>
</fieldset>

</div>
</div>


<div class="form-group">
  <div class=col-sm-10>
<fieldset>
  <%= f.label :number_of_baths %>
  <%= f.number_field :number_of_baths ,  class:"form-control" %>
</fieldset>

</div>
</div>


<div class="form-group">
  <div class=col-sm-10>
<fieldset>
  <%= f.label :number_of_parkings %>
  <%= f.number_field :number_of_parkings ,  class:"form-control" %>
</fieldset>

</div>
</div>



<div class="form-group">
  <div class=col-sm-10>
<fieldset>
  <%= f.label :pets_allowed %>
  <%= f.text_field :pets_allowed ,  class:"form-control" %>
</fieldset>

</div>
</div>

<div class="form-group">
  <div class=col-sm-10>
<fieldset>
  <%= f.label :wifi_present %>
  <%= f.text_field :wifi_present ,  class:"form-control" %>
</fieldset>

</div>
</div>


<div class="form-group">
  <div class=col-sm-10>
<fieldset>
  <%= f.label :smoking_allowed %>
  <%= f.text_field :smoking_allowed ,  class:"form-control" %>
</fieldset>

</div>
</div>


<div class="form-group">
  <div class=col-sm-10>
<fieldset>
  <%= f.label :cancellation_policy %>
  <%= f.text_field :cancellation_policy ,  class:"form-control" %>
</fieldset>
</div>
</div>



<div class="form-group">
  <div class="col-sm-10">
    <br><%= f.submit  'submit', class:"btn btn-primary" %>
  </div>
</div>

<% end %>

app/views/properties/create.html.erb
<h1>Property#create</h1>
<p>Find me in app/views/property/create.html.erb</p>

app/views/properties/destroy.html.erb
<h1>Property#destroy</h1>
<p>Find me in app/views/property/destroy.html.erb</p>

app/views/properties/edit.html.erb
<h2> Edit Property </h2>

<%= render partial: 'form' %>

app/views/properties/home.html.erb
<body class="homepage">
<h2>Welcome to Happy Homes</h2>

<%= link_to 'Click here to Check All Properties', properties_path %>
<br>
<!-- <% @properties.each do |property| %>
<div class="img-responsive">

    <% if property.id % 2 == 0 %>
    <%= link_to property.address, property %>
    <br/>
    <% if property.image.present? %>
    <%= cl_image_tag property.image %>
    <% end %>
    <br/>
    Price : <%= number_to_currency(property.price) %><br/>
    <hr>
    <% end %>
  </div>

<% end %> -->


</body>

app/views/properties/index.html.erb
<h1>Displaying list of properties</h1>


<div class="row">
<% @properties.each do |property| %>
  <div class="col-md-4">
    <%= link_to property.address, property %>
    <br/>
    <%= cl_image_tag property.image %>
    <br/>
    Price : <%= property.price %><br/>
    <hr>
  </div>
<% end %>
</div>

<!-- MAPS -->
    <div id="map"></div>


<script>
function initMap() {

  var prop = <%= @properties.to_json.html_safe %>;

  var myLatLng = {lat: prop[0].latitude, lng: prop[0].longitude };
  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 10,
    center: myLatLng
  });


  for(let i=0; i< prop.length; i++) {
   var myLatLng = {lat: prop[i].latitude, lng: prop[i].longitude };
   var marker = new google.maps.Marker({
    position: myLatLng,
    map: map,
    title: 'locations'
  });
  }
}


var map;
var service;
var infowindow;

function initialize() {
  var prop = <%= @properties.to_json.html_safe %>;

  var pyrmont = new google.maps.LatLng( prop[0].latitude, prop[0].longitude );

  map = new google.maps.Map(document.getElementById('map'), {
      center: pyrmont,
      zoom: 15
    });

  var request = {
    location: pyrmont,
    radius: '500',
    type: ['restaurant']
  };

  service = new google.maps.places.PlacesService(map);
  service.nearbySearch(request, callback);
}

function callback(results, status) {
  if (status == google.maps.places.PlacesServiceStatus.OK) {
    for (var i = 0; i < results.length; i++) {
      var place = results[i];
      createMarker(results[i]);
    }
  }
}
  </script>



<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCB1gVQ_xqsh5cgL2e9KF0N_aCuRyha0pQ&callback=initMap"
<script async defer src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCB1gVQ_xqsh5cgL2e9KF0N_aCuRyha0pQ&callback=initialize"


type="text/javascript"></script>

app/views/properties/new.html.erb
<h5>New Property</h5>
<%= render partial: 'form' %>

app/views/properties/show.html.erb
<h1> <%=@property.property_type %> at <%=@property.address %></h1>
  <br/>
  <%= cl_image_tag @property.image %>

  <br/>
      <%= link_to 'More pics', property_photos_path(@property) %>
  <hr>


<table class="table table-striped">
<tr>
  <td><span class="glyphicon glyphicon-home" aria-hidden="true"></span>
  Type : <%= @property.property_type %></td>
  <td><i class="fa fa-car" aria-hidden="true"></i>
  Parkings:             <%= @property.number_of_parkings %></td>
  <td><i class="fa fa-bath" aria-hidden="true"></i>
  Baths:                <%= @property.number_of_baths %></td>
</tr>
<tr>
  <td><span class="glyphicon glyphicon-bed" aria-hidden="true"></span>
  Beds:                 <%= @property.number_of_beds %></td>
  <td><i class="fa fa-github-alt" aria-hidden="true"></i>
  Pets :                <%= @property.pets_allowed %></td>
  <td><i class="fa fa-wifi" aria-hidden="true"></i>
  WiFi:                 <%= @property.wifi_present %></td>
</tr>
<tr>
  <td><span class="glyphicon glyphicon-fire" aria-hidden="true"></span>
  Smoking:              <%= @property.smoking_allowed %></td>
  <td></td>
  <td></td>
</tr>
</table>



  Description:          <%= @property.description %><br/>
  <br/><hr>
  <%  if(@current_user == @property.user) %>
  <small> Your Property </small><br>
  <%= link_to 'Edit' , edit_property_path( @property )%> |
  <%= link_to 'Delete' , property_path( @property ), method: 'delete'%>
  <hr><hr><hr>
  <% else %>

  <%= link_to 'Contact the Owner', @property.user %>
  <hr>
  <% end %>


  <p><strong>Tags</strong>:</p>
  <ul>
  <% @property.tags.each do |tag| %>
    <li>
      <%= link_to tag.name, property_tag_path(@property) %>
    </li>
  <% end %>
  </ul>
  <hr>

  <p><strong>Bookings</strong>:</p>
  <ul>
  <% @property.bookings.each do |booking| %>
    <li>
      Booked from <%= Date.parse(booking.check_in) %> to  <%= Date.parse(booking.check_out) %>
      <%= link_to 'Delete Booking' , property_booking_path(@property, booking), method: 'delete' %>
    </li>
  <% end %>
  </ul>

  <%= link_to 'Make a Booking' , new_property_booking_path(@property) %>
  <hr>

  <!-- <%= link_to 'See More Photos', property_photos_path(@property) %> -->