config/routes.rb
Rails.application.routes.draw do

  # Root Path definition
  root to: 'properties#home'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  get '/profile' => 'pages#profile'
  get '/admin'   => 'pages#admin_party'

  resources :properties do
    resources :bookings
    resources :photos
    resources :tags

  end

  # resources :photos
  resources :users
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :property , optional: true
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController



  def new
      @property = Property.find params[:property_id]
      @photo = Photo.new
  end


  def index
    @property = Property.find params[:property_id]
    @photos = @property.photos
  end


  def create

    photo = Property.find params[:property_id]
    p = Photo.new

    if params[:file].present?
      req = Cloudinary::Uploader.upload(params[:file])
      p.image_url = req["public_id"]
    end
    p.save
    # Photo.create photo_params
    redirect_to property_photo_path
  end



  def show
    @property = Property.find params[:property_id]
    @photos = @property.photos
  end


  def destroy
    property =  Property.find params[:property_id]
    photo = Photo.find params[:id]
    photo.destroy
    redirect_to property_photos_path
  end



  private
   def photo_params
     params.require(:photo).permit(:image)
   end
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/views/photos/_form.html.erb
<%= form_for [@property, @photo] , html: {multipart: true} do |f| %>
<fieldset>
  <%= f.label :image_url %>
  <%= f.cl_image_upload :image_url %>
</fieldset>

<%= f.submit %>
<% end %>

app/views/photos/create.html.erb
<h1>Photo#create</h1>
<p>Find me in app/views/photo/create.html.erb</p>

app/views/photos/destroy.html.erb
<h1>Photo#destroy</h1>
<p>Find me in app/views/photo/destroy.html.erb</p>

app/views/photos/index.html.erb
<h1> More pics... </h1>



<% if(@current_user == @property.user) %>
<%= link_to 'Add an image', new_property_photo_path %>
<% end %>
<hr>
<%= link_to 'Back to Property', @property %>
<hr>


<div class="row">
<% @photos.each do |p| %>
    <%= image_tag p.image_url %><br><br>
    <br>
    <% if(@current_user == @property.user) %>
        <p><%= link_to 'Delete' , property_photo_path( @property , p), method: 'delete'%></p>
    <% end %>
    <% end %>
  </div>

app/views/photos/new.html.erb
<h5>Adding new Photo</h5>
<%= render partial: 'form' %>

app/views/photos/show.html.erb
<p>More Photos of Property at
<%=  @property.address  %><br>
</p>



<% @photos.each do |p| %>
  <%= image_tag p.image_url %>
<br>
<% end %>