config/routes.rb
Rails.application.routes.draw do

  # Root Path definition
  root to: 'properties#home'

  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  get '/profile' => 'pages#profile'
  get '/admin'   => 'pages#admin_party'

  resources :properties do
    resources :bookings
    resources :photos
    resources :tags

  end

  # resources :photos
  resources :users
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

  <link href="https://fonts.googleapis.com/css?family=Supermercado+One" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Orbitron" rel="stylesheet">


  <title>RentalMarketplace</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
  </head>

  <body>
  <div class="container">

  <nav>
    <ul>
    <div class="logo">
      Happy Homes<sup class="small">&reg;</sup>
       <div class="triangle"></div> <div class="triangle two"></div>
       <br>
       <li><%= link_to "Host Your Property", new_property_path, class: 'btn btn-info btn-lg' %></li>

    </div><br>
      <li><%= link_to "Home"   , root_path, class: 'btn btn-primary' %></li>
      <li><%= link_to "Properties"   , properties_path, class: 'btn btn-primary' %></li>
      <% if @current_user.present? %>

      <li><%= link_to "Your Profile",@current_user, class: 'btn btn-primary' %></li>
      <li><%= link_to "Logout", login_path, class: 'btn btn-primary', method: :delete %></li>

      <% else %>
        <li><%= link_to "Login", login_path, class: 'btn btn-primary' %></li>
        <li><%= link_to "Sign Up", new_user_path, class: 'btn btn-primary' %></li>
      <% end %>

      </ul>
    </nav>
  <% if @current_user.present? %>
    <h4> Welcome, <%= @current_user.full_name %> </h4>
  <% end %>
    <%= yield %>
  </div>

  </div>
  </body>
</html>